version: '3.1'

services:
 
  mongo:
    image: arm64v8/mongo
    restart: always
    volumes:
      - ./mongodata:/data/db
      - ./mongoconfig:/data/configdb

  mongo-express:
    image: arm64v8/mongo-express
    restart: always
    ports:
      - 8081:8081
